"""Auto-repair and structural validation helpers for Power BI PBIP / PBIR projects.

Public API
----------
sanitize_pbip_starter(starter)         — 6-phase in-place fixer, returns list of fix descriptions
check_graph_ambiguity(graph)           — BFS: reject models with two paths between same tables
parse_tmdl_relationships(model_tmdl)   — extract FK graph from model.tmdl text
check_relationship_coherence(schema)   — validate data_schema.json FK graph
"""

from __future__ import annotations

import json
import logging
import re
import shutil
from pathlib import Path
from typing import Any

LOGGER = logging.getLogger(__name__)

# ── Schema URLs ────────────────────────────────────────────────────
# Verified from a blank PBIP project generated by Power BI Desktop 2.154 (May 2026).

_SCHEMAS = {
    "pbip": "https://developer.microsoft.com/json-schemas/fabric/pbip/pbipProperties/1.0.0/schema.json",
    "pbir": "https://developer.microsoft.com/json-schemas/fabric/item/report/definitionProperties/2.0.0/schema.json",
    "version": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/versionMetadata/1.0.0/schema.json",
    "report": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.3.0/schema.json",
    "pages": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/pagesMetadata/1.1.0/schema.json",
    "page": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/2.1.0/schema.json",
    "visual": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/1.0.0/schema.json",
    "pbism": "https://developer.microsoft.com/json-schemas/fabric/item/semanticModel/definitionProperties/1.0.0/schema.json",
}

_THEME_FILENAME = "CY26SU05.json"  # May 2026 release theme

# Maps wrong/old visual type names used by LLMs → correct PBIR names.
_VISUAL_TYPE_MAP: dict[str, str] = {
    "columnChart": "clusteredColumnChart",
    "barChart": "clusteredBarChart",
    "stackedColumn": "stackedColumnChart",
    "stackedBar": "stackedBarChart",
    "column": "clusteredColumnChart",
    "bar": "clusteredBarChart",
}


# ── Canonical JSON builders ────────────────────────────────────────


def _canonical_version_json() -> dict[str, Any]:
    return {"$schema": _SCHEMAS["version"], "version": "2.0.0"}


def _canonical_report_json() -> dict[str, Any]:
    return {
        "$schema": _SCHEMAS["report"],
        "themeCollection": {
            "baseTheme": {
                "name": "CY26SU05",
                "reportVersionAtImport": {"visual": "2.9.0", "report": "3.3.0", "page": "2.3.1"},
                "type": "SharedResources",
            }
        },
        "objects": {
            "section": [
                {"properties": {"verticalAlignment": {"expr": {"Literal": {"Value": "'Top'"}}}}}
            ]
        },
        "resourcePackages": [
            {
                "name": "SharedResources",
                "type": "SharedResources",
                "items": [
                    {"name": "CY26SU05", "path": "BaseThemes/CY26SU05.json", "type": "BaseTheme"}
                ],
            }
        ],
        "settings": {
            "useStylableVisualContainerHeader": True,
            "exportDataMode": "AllowSummarized",
            "defaultDrillFilterOtherVisuals": True,
            "allowChangeFilterTypes": True,
            "useEnhancedTooltips": True,
            "useDefaultAggregateDisplayName": True,
        },
    }


def _canonical_pages_json(page_ids: list[str]) -> dict[str, Any]:
    first = page_ids[0] if page_ids else ""
    return {"$schema": _SCHEMAS["pages"], "pageOrder": page_ids, "activePageName": first}


def _canonical_page_json(page_id: str, display_name: str = "Page 1") -> dict[str, Any]:
    """page.json for PBI Desktop 2.154 — NO config field, displayOption is a string."""
    return {
        "$schema": _SCHEMAS["page"],
        "name": page_id,
        "displayName": display_name,
        "displayOption": "FitToPage",
        "height": 720,
        "width": 1280,
    }


def _placeholder_visual(name: str, position: dict[str, Any]) -> dict[str, Any]:
    """Return a valid PBIR 1.0.0 visual container dict for an empty textbox."""
    return {
        "$schema": _SCHEMAS["visual"],
        "name": name,
        "position": {
            "x": position.get("x", 0),
            "y": position.get("y", 0),
            "z": position.get("z", 1000),
            "height": position.get("height", 120),
            "width": position.get("width", 280),
            "tabOrder": position.get("tabOrder", 0),
        },
        "visual": {"visualType": "textbox"},
    }


# ── PBIR structure migration (pre-2.154 → 2.154+) ─────────────────


def _migrate_pbir_structure(starter: Path, fixes: list[str]) -> None:
    """Migrate Assessment.Report from pre-2.154 layout to the 2.154+ layout.

    Pre-2.154:  report.json and pages/ sit at the Assessment.Report/ root.
    2.154+:     both live inside Assessment.Report/definition/;
                a new definition/version.json is required;
                the theme is named CY26SU05.json instead of theme.json.
    """
    report_dir = starter / "Assessment.Report"
    if not report_dir.exists():
        return

    def_dir = report_dir / "definition"
    old_report = report_dir / "report.json"
    old_pages = report_dir / "pages"

    if (def_dir / "report.json").exists():
        pass  # already migrated — still check theme below
    else:
        if old_report.exists() or old_pages.exists():
            def_dir.mkdir(exist_ok=True)

            ver_f = def_dir / "version.json"
            if not ver_f.exists():
                ver_f.write_text(
                    json.dumps(_canonical_version_json(), indent=2, ensure_ascii=False),
                    encoding="utf-8",
                )
                fixes.append("created definition/version.json")

            if old_report.exists():
                (def_dir / "report.json").write_text(
                    old_report.read_text(encoding="utf-8"), encoding="utf-8"
                )
                old_report.unlink()
                fixes.append("migrated report.json → definition/report.json")

            if old_pages.exists():
                new_pages = def_dir / "pages"
                if not new_pages.exists():
                    shutil.copytree(old_pages, new_pages)
                shutil.rmtree(old_pages)
                fixes.append("migrated pages/ → definition/pages/")

    theme_base = report_dir / "StaticResources" / "SharedResources" / "BaseThemes"
    if theme_base.exists():
        new_theme = theme_base / _THEME_FILENAME
        if not new_theme.exists():
            for old_theme in theme_base.iterdir():
                if old_theme.is_file() and old_theme.suffix == ".json":
                    old_theme.rename(new_theme)
                    fixes.append(f"renamed {old_theme.name} → {_THEME_FILENAME}")
                    break


# ── Report page/visual JSON repair ────────────────────────────────


def _sanitize_report_pages(starter: Path, fixes: list[str]) -> None:
    """Repair all PBIR report definition files to match PBI Desktop 2.154 format."""
    report_dir = starter / "Assessment.Report"
    if not report_dir.exists():
        return

    pages_root = report_dir / "definition" / "pages"
    if not pages_root.exists():
        pages_root = report_dir / "pages"  # fallback: definition/ not yet migrated

    # version.json: version "2.0.0", correct schema URL
    def_ver = report_dir / "definition" / "version.json"
    if def_ver.exists():
        try:
            data = json.loads(def_ver.read_text(encoding="utf-8"))
            correct = _canonical_version_json()
            if data != correct:
                def_ver.write_text(
                    json.dumps(correct, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                fixes.append("fixed definition/version.json (version 2.0.0 + correct $schema)")
        except (json.JSONDecodeError, OSError):
            pass

    # definition/report.json: flat format, no config-string
    def_report = report_dir / "definition" / "report.json"
    if def_report.exists():
        try:
            data = json.loads(def_report.read_text(encoding="utf-8"))
            correct = _canonical_report_json()
            if data.get("$schema") != correct["$schema"] or "config" in data:
                def_report.write_text(
                    json.dumps(correct, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                fixes.append("rewrote definition/report.json to flat PBI 2.154 format")
        except (json.JSONDecodeError, OSError):
            pass

    # pages.json: pageOrder+activePageName format
    pages_idx = pages_root / "pages.json"
    if pages_idx.exists():
        try:
            data = json.loads(pages_idx.read_text(encoding="utf-8"))
            schema_ok = data.get("$schema") == _SCHEMAS["pages"]
            has_new_format = "pageOrder" in data
            if not schema_ok or not has_new_format:
                if "pages" in data and not has_new_format:
                    page_ids = [p["name"] for p in data["pages"] if "name" in p]
                else:
                    page_ids = data.get("pageOrder", [])
                new_data = _canonical_pages_json(page_ids)
                pages_idx.write_text(
                    json.dumps(new_data, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                fixes.append("converted pages.json to pageOrder format (PBI 2.154)")
        except (json.JSONDecodeError, OSError):
            pass

    # Normalize page IDs to lowercase.
    # PBI Desktop generates lowercase page IDs for PBIR format; uppercase IDs
    # cause "failed to load report" because the parser validates ID format.
    if pages_idx.exists():
        try:
            data = json.loads(pages_idx.read_text(encoding="utf-8"))
            page_order = data.get("pageOrder", [])
            id_map = {pid: pid.lower() for pid in page_order if pid != pid.lower()}
            if id_map:
                # Rename page directories (two-step to handle case-insensitive filesystems)
                for old_id, new_id in id_map.items():
                    old_dir = pages_root / old_id
                    tmp_dir = pages_root / (new_id + "_casefix_tmp")
                    new_dir = pages_root / new_id
                    if old_dir.exists():
                        old_dir.rename(tmp_dir)
                        tmp_dir.rename(new_dir)
                # Update pages.json
                data["pageOrder"] = [id_map.get(p, p) for p in page_order]
                if data.get("activePageName") in id_map:
                    data["activePageName"] = id_map[data["activePageName"]]
                pages_idx.write_text(
                    json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                fixes.append(f"lowercased {len(id_map)} page ID(s) in pages.json and directories")
        except (json.JSONDecodeError, OSError):
            pass

    # page.json: no config field, displayOption is a string
    for page_json_f in report_dir.rglob("page.json"):
        try:
            data = json.loads(page_json_f.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        page_name = data.get("name", page_json_f.parent.name)
        needs_fix = (
            data.get("$schema") != _SCHEMAS["page"]
            or "config" in data
            or "filters" in data
            or data.get("displayOption") != "FitToPage"
            or page_name != page_name.lower()
        )
        if needs_fix:
            corrected = _canonical_page_json(
                page_name.lower(),
                data.get("displayName", "Page 1"),
            )
            page_json_f.write_text(
                json.dumps(corrected, indent=2, ensure_ascii=False), encoding="utf-8"
            )
            fixes.append(f"fixed {page_json_f.parent.name}/page.json to PBI 2.154 format")

    # visual.json: migrate old format (config string) → PBIR 1.0.0 (visual object),
    # fix visual type names, add $schema.
    # In PBIR schema 1.0.0, additionalProperties=false; "config", "filters", "tabOrder"
    # (at top level) are all invalid. The visual definition lives in a "visual" object,
    # and tabOrder moves inside "position".
    for vis_json in report_dir.rglob("visual.json"):
        try:
            data = json.loads(vis_json.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue

        changed = False
        pos = data.get("position", {"x": 0, "y": 0, "z": 1000, "height": 120, "width": 280})

        # Strip any field not in the visualContainer/1.0.0 schema (additionalProperties:false).
        # Common LLM mistakes: "config" (old format string), "filters" (old string),
        # "tabOrder" and "displayState" (should be inside position or removed entirely).
        _VALID_VISUAL_KEYS = {
            "$schema",
            "name",
            "position",
            "visual",
            "visualGroup",
            "parentGroupName",
            "filterConfig",
            "isHidden",
            "annotations",
            "howCreated",
        }
        invalid_keys = [k for k in list(data) if k not in _VALID_VISUAL_KEYS]
        if invalid_keys:
            # Before discarding "config", extract visual type for migration.
            if "config" in data and "visual" not in data:
                old_vtype = "textbox"
                try:
                    cfg = json.loads(data["config"])
                    old_vtype = cfg.get("singleVisual", {}).get("visualType", "textbox")
                except (json.JSONDecodeError, TypeError):
                    pass
                data["visual"] = {"visualType": old_vtype}

            # Move tabOrder into position if present at root.
            if "tabOrder" in data and "tabOrder" not in pos:
                pos["tabOrder"] = data["tabOrder"]
                data["position"] = pos

            for k in invalid_keys:
                data.pop(k, None)

            changed = True
            fixes.append(
                f"removed invalid root field(s) {invalid_keys} from "
                f"{vis_json.parent.name}/visual.json (PBIR 1.0.0)"
            )

        # Fix wrong visual type names in the 1.0.0 visual object.
        vis_obj = data.get("visual", {})
        vtype = vis_obj.get("visualType", "")
        if vtype in _VISUAL_TYPE_MAP:
            vis_obj["visualType"] = _VISUAL_TYPE_MAP[vtype]
            data["visual"] = vis_obj
            changed = True
            fixes.append(
                f"fixed visualType {vtype!r} → {_VISUAL_TYPE_MAP[vtype]!r} "
                f"in {vis_json.parent.name}/visual.json"
            )

        # Add $schema if missing.
        if data.get("$schema") != _SCHEMAS["visual"]:
            data["$schema"] = _SCHEMAS["visual"]
            changed = True
            fixes.append(f"added $schema to {vis_json.parent.name}/visual.json")

        # Add missing queryRef to projections.
        # PBIR 1.0.0 schema requires queryRef = "Entity.Property" on every projection.
        query_state = data.get("visual", {}).get("query", {}).get("queryState", {})
        qref_added = False
        for role_obj in query_state.values():
            for proj in role_obj.get("projections", []):
                if "queryRef" in proj:
                    continue
                field = proj.get("field", {})
                for ftype in ("Measure", "Column"):
                    if ftype in field:
                        fdef = field[ftype]
                        entity = fdef.get("Expression", {}).get("SourceRef", {}).get("Entity", "")
                        prop = fdef.get("Property", "")
                        if entity and prop:
                            proj["queryRef"] = f"{entity}.{prop}"
                            qref_added = True
                        break
        if qref_added:
            changed = True
            fixes.append(f"added missing queryRef(s) to {vis_json.parent.name}/visual.json")

        if changed:
            vis_json.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

    # Ensure the CY26SU05 base theme file has valid JSON content.
    # An empty {} causes PBI Desktop to fail when loading the report.
    # A minimal {"name": "..."} is sufficient for PBI to fall back to default styling.
    theme_base = report_dir / "StaticResources" / "SharedResources" / "BaseThemes"
    if theme_base.exists():
        for theme_file in theme_base.iterdir():
            if theme_file.suffix != ".json":
                continue
            try:
                content = json.loads(theme_file.read_text(encoding="utf-8"))
                if not content.get("name"):
                    content["name"] = theme_file.stem
                    theme_file.write_text(json.dumps(content, ensure_ascii=False), encoding="utf-8")
                    fixes.append(f"added missing name to theme file {theme_file.name}")
            except (json.JSONDecodeError, OSError):
                pass

    # Inject a placeholder textbox for any page that has zero visual containers.
    # Power BI crashes with "Cannot read properties of undefined (reading 'visualContainers')"
    # when a page has no visuals — the placeholder prevents that crash.
    for page_json_f in report_dir.rglob("page.json"):
        pid = page_json_f.parent.name
        visuals_dir = page_json_f.parent / "visuals"
        has_visuals = visuals_dir.exists() and any(p.is_dir() for p in visuals_dir.iterdir())
        if not has_visuals:
            ph_dir = visuals_dir / "starter_placeholder"
            ph_dir.mkdir(parents=True, exist_ok=True)
            pos = {"x": 490, "y": 330, "z": 1000, "height": 60, "width": 300, "tabOrder": 0}
            vis = _placeholder_visual("starter_placeholder", pos)
            (ph_dir / "visual.json").write_text(
                json.dumps(vis, indent=2, ensure_ascii=False), encoding="utf-8"
            )
            fixes.append(f"injected placeholder visual for empty page '{pid}'")

    # Remove page directories not listed in pages.json
    pages_index = pages_root / "pages.json"
    if pages_index.exists():
        try:
            idx = json.loads(pages_index.read_text())
            listed = (
                set(idx["pageOrder"])
                if "pageOrder" in idx
                else {p["name"] for p in idx.get("pages", [])}
            )
            for d in pages_root.iterdir():
                if d.is_dir() and d.name not in listed:
                    shutil.rmtree(d, ignore_errors=True)
                    fixes.append(f"removed orphan page '{d.name}' (not in pages.json)")
        except (json.JSONDecodeError, OSError):
            pass


# ── Main sanitizer (6 phases) ──────────────────────────────────────


def sanitize_pbip_starter(starter: Path) -> list[str]:
    """Fix common LLM mistakes in generated PBIP files in-place.

    Returns a list of human-readable fix descriptions for logging.
    Idempotent: safe to call multiple times on the same directory.

    Phases
    ------
    0   Migrate Assessment.Report to Power BI Desktop 2.154 PBIR layout
    0b  Fix definition.pbism (version 4.2, $schema)
    0c  Fix Assessment.pbip ($schema, enableAutoRecovery)
    0d  Fix definition.pbir ($schema, remove byConnection: null)
    1   Fix TMDL files (remove createOrReplace, fix path separators)
    2   Fix database.tmdl / model.tmdl content confusion
    3   Fix definition.pbir version (must be "4.0")
    4   Convert hardcoded File.Contents paths → DataPath parameter
    5   Ensure expressions/DataPath.tmdl exists when DataPath is used
    6   Repair report page and visual JSON configs
    """
    fixes: list[str] = []

    # Phase 0 — upgrade to Power BI Desktop 2.154 PBIR directory layout
    _migrate_pbir_structure(starter, fixes)

    # Phase 0b — fix definition.pbism
    pbism_file = starter / "Assessment.SemanticModel" / "definition.pbism"
    if pbism_file.exists():
        try:
            pbism = json.loads(pbism_file.read_text(encoding="utf-8"))
            correct_pbism = {"$schema": _SCHEMAS["pbism"], "version": "4.2", "settings": {}}
            if (
                pbism.get("$schema") != _SCHEMAS["pbism"]
                or pbism.get("version") != "4.2"
                or pbism.get("settings") != {}
            ):
                pbism_file.write_text(
                    json.dumps(correct_pbism, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                fixes.append("fixed definition.pbism (version 4.2 + $schema)")
        except (json.JSONDecodeError, OSError):
            pass

    # Phase 0c — fix Assessment.pbip
    # The artifacts array must contain ONLY the report entry.
    # The semantic model is linked via definition.pbir — listing it again in
    # artifacts causes PBI Desktop to see a duplicate model reference and refuse to open.
    pbip_file = starter / "Assessment.pbip"
    if pbip_file.exists():
        try:
            pbip = json.loads(pbip_file.read_text(encoding="utf-8"))
            report_entry = next(
                (a for a in pbip.get("artifacts", []) if "report" in a),
                {"report": {"path": "Assessment.Report"}},
            )
            correct_artifacts = [report_entry]
            if (
                pbip.get("$schema") != _SCHEMAS["pbip"]
                or pbip.get("settings", {}).get("enableAutoRecovery") is not True
                or pbip.get("artifacts") != correct_artifacts
            ):
                pbip["$schema"] = _SCHEMAS["pbip"]
                pbip.setdefault("version", "1.0")
                pbip["settings"] = {"enableAutoRecovery": True}
                pbip["artifacts"] = correct_artifacts
                pbip_file.write_text(
                    json.dumps(pbip, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                fixes.append(
                    "fixed Assessment.pbip ($schema + enableAutoRecovery + single report artifact)"
                )
        except (json.JSONDecodeError, OSError):
            pass

    # Phase 0d — fix definition.pbir: add $schema, remove byConnection: null
    pbir_file = starter / "Assessment.Report" / "definition.pbir"
    if pbir_file.exists():
        try:
            pbir = json.loads(pbir_file.read_text(encoding="utf-8"))
            dr = pbir.get("datasetReference", {})
            bp = dr.get("byPath", {})
            if pbir.get("$schema") != _SCHEMAS["pbir"] or "byConnection" in dr:
                pbir["$schema"] = _SCHEMAS["pbir"]
                pbir["datasetReference"] = {
                    "byPath": {"path": bp.get("path", "../Assessment.SemanticModel")}
                }
                pbir_file.write_text(
                    json.dumps(pbir, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                fixes.append("fixed definition.pbir ($schema + removed byConnection)")
        except (json.JSONDecodeError, OSError):
            pass

    tmdl_dir = starter / "Assessment.SemanticModel" / "definition"
    if not tmdl_dir.exists():
        return fixes

    # Phase 1 — fix all TMDL files
    for tmdl_file in tmdl_dir.rglob("*.tmdl"):
        text = tmdl_file.read_text(encoding="utf-8")
        original = text

        text = re.sub(r"^\s*createOrReplace\s*\n+", "", text, flags=re.IGNORECASE)
        if text != original:
            fixes.append(f"removed 'createOrReplace' from {tmdl_file.name}")

        def _fix_path(m: re.Match[str]) -> str:
            return f'File.Contents("{m.group(1).replace("/", chr(92))}")'

        patched = re.sub(r'File\.Contents\("([^"]+)"\)', _fix_path, text)
        if patched != text:
            fixes.append(f"fixed path separators in {tmdl_file.name}")
            text = patched

        if text != original:
            tmdl_file.write_text(text, encoding="utf-8")

    # Phase 2 — fix database.tmdl / model.tmdl content confusion
    db_file = tmdl_dir / "database.tmdl"
    model_file = tmdl_dir / "model.tmdl"

    if db_file.exists():
        db_text = db_file.read_text(encoding="utf-8")
        if not db_text.lstrip().startswith("database "):
            model_text = model_file.read_text(encoding="utf-8") if model_file.exists() else ""
            if "culture:" not in model_text and "culture:" in db_text:
                model_file.write_text(db_text, encoding="utf-8")
                fixes.append("rescued model settings from database.tmdl → model.tmdl")
            db_file.write_text("database Database\n\tcompatibilityLevel: 1601\n", encoding="utf-8")
            fixes.append("replaced database.tmdl with canonical two-line content")

    # Phase 2b — remove all `ref` declarations from model.tmdl.
    # In TMDL v4, tables and expressions are auto-discovered from their respective
    # subdirectories. Any `ref table` or `ref expression` line in the model document
    # triggers "Unexpected line type: ReferenceObject!" in PBI Desktop.
    if model_file.exists():
        text = model_file.read_text(encoding="utf-8")
        patched = re.sub(r"^\t*ref\s+\S.*\n?", "", text, flags=re.MULTILINE)
        if patched != text:
            fixes.append(
                "removed ref table/expression line(s) from model.tmdl (auto-discovered in TMDL v4)"
            )
            text = patched
        if text != model_file.read_text(encoding="utf-8"):
            model_file.write_text(text, encoding="utf-8")

    # Phase 3 — fix definition.pbir version (must be "4.0")
    pbir_file = starter / "Assessment.Report" / "definition.pbir"
    if pbir_file.exists():
        try:
            pbir = json.loads(pbir_file.read_text(encoding="utf-8"))
            if pbir.get("version") != "4.0":
                old_ver = pbir.get("version")
                pbir["version"] = "4.0"
                pbir_file.write_text(json.dumps(pbir, ensure_ascii=False), encoding="utf-8")
                fixes.append(f"fixed definition.pbir version {old_ver!r} → '4.0'")
        except (json.JSONDecodeError, OSError):
            pass

    # Phase 4 — convert hardcoded relative data paths to DataPath parameter
    _HARDCODED_PATH_RE = re.compile(r'File\.Contents\("[.][.][/\\]data[/\\]([^"]+)"\)')
    datapath_used = False
    for tmdl_file in tmdl_dir.rglob("*.tmdl"):
        if tmdl_file.name in ("model.tmdl", "database.tmdl"):
            continue
        text = tmdl_file.read_text(encoding="utf-8")
        if "DataPath" in text:
            datapath_used = True
            continue
        patched = _HARDCODED_PATH_RE.sub(
            lambda m: f'File.Contents(DataPath & "\\{m.group(1)}")', text
        )
        if patched != text:
            tmdl_file.write_text(patched, encoding="utf-8")
            fixes.append(f"converted hardcoded path → DataPath in {tmdl_file.name}")
            datapath_used = True

    # Phase 4b — fix double backslash in DataPath M expressions.
    # The LLM sometimes writes DataPath & "\\file.csv" (two backslashes) instead
    # of DataPath & "\file.csv" (one). Windows File.Contents rejects the double path.
    _DOUBLE_BACKSLASH_RE = re.compile(r'(DataPath\s*&\s*")(\\\\)')
    for tmdl_file in tmdl_dir.rglob("*.tmdl"):
        text = tmdl_file.read_text(encoding="utf-8")
        patched = _DOUBLE_BACKSLASH_RE.sub(r"\1\\", text)
        if patched != text:
            tmdl_file.write_text(patched, encoding="utf-8")
            fixes.append(f"fixed double backslash in DataPath expression in {tmdl_file.name}")

    # Phase 5 — ensure expressions/DataPath.tmdl exists when DataPath is referenced
    import uuid as _uuid

    expr_dir = tmdl_dir / "expressions"
    datapath_expr = expr_dir / "DataPath.tmdl"
    if datapath_used and not datapath_expr.exists():
        expr_dir.mkdir(parents=True, exist_ok=True)
        datapath_expr.write_text(
            'expression DataPath = "C:\\data" meta'
            ' [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]\n'
            f"\tlineageTag: {_uuid.uuid4()}\n",
            encoding="utf-8",
        )
        fixes.append("created missing expressions/DataPath.tmdl")

    # Phase 6 — repair report page and visual JSON configs
    _sanitize_report_pages(starter, fixes)

    return fixes


# ── Relationship graph helpers ─────────────────────────────────────


def check_graph_ambiguity(graph: dict[str, set[str]]) -> tuple[bool, str]:
    """BFS check: return (True, '') if no pair of nodes has >1 directed path.

    Power BI rejects models where two tables are connected by both a direct FK
    and a transitive chain (A→B→C plus A→C). The error message names the direct
    edge, the full transitive chain, and the exact fix to make the retry actionable.
    """
    from collections import deque

    for u, neighbors in graph.items():
        for v in list(neighbors):
            visited: set[str] = {u}
            parent: dict[str, str] = {}
            queue: deque[str] = deque()
            for nb in neighbors:
                if nb != v and nb not in visited:
                    visited.add(nb)
                    parent[nb] = u
                    queue.append(nb)

            while queue:
                cur = queue.popleft()
                if cur == v:
                    chain, node = [v], v
                    while node in parent:
                        node = parent[node]
                        chain.append(node)
                    chain_str = " → ".join(reversed(chain))
                    return (
                        False,
                        f"AMBIGUOUS RELATIONSHIP: '{u}' → '{v}' exists as a direct FK "
                        f"AND as the transitive chain [{chain_str}]. "
                        f"Power BI rejects models with two paths between the same tables. "
                        f"FIX: in the '{u}' table, set fk_to: null for the column that "
                        f"points directly to '{v}' (keep the column value, just remove "
                        f"the FK arrow). The transitive chain [{chain_str}] is sufficient.",
                    )
                for nb in graph.get(cur, set()):
                    if nb not in visited:
                        visited.add(nb)
                        parent[nb] = cur
                        queue.append(nb)

    return True, ""


def parse_tmdl_relationships(model_tmdl: str) -> dict[str, set[str]]:
    """Parse relationship blocks from model.tmdl; return a directed adjacency dict.

    Handles both TMDL formats:
      fromColumn: FactTable.col  /  toColumn: DimTable.col
    """
    graph: dict[str, set[str]] = {}
    from_re = re.compile(r"fromColumn:\s*(\w+)\.", re.IGNORECASE)
    to_re = re.compile(r"toColumn:\s*(\w+)\.", re.IGNORECASE)

    in_rel = False
    from_table = to_table = None
    for line in model_tmdl.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("relationship "):
            in_rel = True
            from_table = to_table = None
            continue
        if in_rel:
            m = from_re.match(stripped)
            if m:
                from_table = m.group(1)
            m = to_re.match(stripped)
            if m:
                to_table = m.group(1)
            if not stripped or (
                not stripped.startswith("#")
                and ":" not in stripped
                and not stripped.lower().startswith("relationship")
            ):
                if from_table and to_table and from_table != to_table:
                    graph.setdefault(from_table, set()).add(to_table)
                in_rel = False
                from_table = to_table = None

    if in_rel and from_table and to_table and from_table != to_table:
        graph.setdefault(from_table, set()).add(to_table)

    return graph


def check_relationship_coherence(schema: dict[str, Any]) -> tuple[bool, str]:
    """Verify the FK graph in data_schema.json has no alternative paths."""
    graph: dict[str, set[str]] = {}
    for file_info in schema.get("files", []):
        from_table = file_info["filename"].replace(".csv", "")
        graph.setdefault(from_table, set())
        for col in file_info.get("columns", []):
            fk_to = col.get("fk_to")
            if fk_to and str(fk_to).lower() not in ("null", "none", ""):
                to_table = str(fk_to).split(".")[0].replace(".csv", "").strip()
                if to_table and to_table != from_table:
                    graph[from_table].add(to_table)
    return check_graph_ambiguity(graph)
